name: Export Power Platform Solution

on:
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Node.js to v16 (to avoid pac CLI bug)
      uses: actions/setup-node@v3
      with:
          node-version: 16
          
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '6.x'
          
    - name: Install Power Platform CLI
      run: |
        dotnet tool install --global Microsoft.PowerApps.CLI.Tool
     

    - name: Authenticate with Power Platform
      run: |
        pac auth create --applicationId ${{ secrets.POWERPLATFORM_CLIENT_ID}} --clientSecret ${{ secrets.POWERPLATFORM_CLIENT_SECRET }} --tenant ${{ secrets.POWERPLATFORM_TENANT_ID }} --url ${{ secrets.DEV_ENV_URL }}


    - name: Export Solution
      run: |
        mkdir Solution
        pac solution export --name ${{ secrets.SOLUTION_NAME }} --path ./solution/${{ secrets.SOLUTION_NAME }}.zip --managed false

    - name: Unpack solution
      run: |
        pac solution unpack --zipfile ./solution/${{ secrets.SOLUTION_NAME }}.zip --folder ./solution/unpacked --allowDelete

    - name: Commit & push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add solution/unpacked
        git commit -m "Exported solution ${{ secrets.SOLUTION_NAME }} on $(date)"
        git push
